"""empty message

Revision ID: d3b4861984b2
Revises: 8d6eeb7f218a
Create Date: 2024-07-27 21:35:26.291285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b4861984b2'
down_revision = '8d6eeb7f218a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_character', sa.Integer(), nullable=True),
    sa.Column('favorite_planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['favorite_planet'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'favorite_character', 'favorite_planet')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
